# Generated by Django 4.0.2 on 2022-02-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('orderState', models.IntegerField(default=0)),
                ('sellerAddress', models.CharField(max_length=256)),
                ('sellerPhone', models.CharField(max_length=256)),
                ('sellerName', models.CharField(max_length=256)),
                ('seller_id', models.CharField(max_length=256)),
                ('buyersAddress', models.CharField(max_length=256)),
                ('buyersPhone', models.CharField(max_length=256)),
                ('buyersName', models.CharField(max_length=256)),
                ('buyers_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crdate', models.DateField(auto_now_add=True)),
                ('price', models.CharField(max_length=256)),
                ('imgUrl', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('seller_id', models.CharField(max_length=256)),
            ],
        ),
    ]
