# Generated by Django 4.0.2 on 2022-03-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('orderState', models.IntegerField(default=0)),
                ('sellerAddress', models.CharField(max_length=256)),
                ('sellerPhone', models.CharField(max_length=256)),
                ('sellerName', models.CharField(max_length=256)),
                ('seller_id', models.CharField(max_length=256)),
                ('buyersAddress', models.CharField(max_length=256)),
                ('buyersPhone', models.CharField(max_length=256)),
                ('buyersName', models.CharField(max_length=256)),
                ('buyers_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdate', models.DateField(auto_now_add=True)),
                ('price', models.CharField(max_length=256)),
                ('imgUrl', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('seller_id', models.CharField(max_length=256)),
            ],
        ),
    ]
