# Generated by Django 4.0.2 on 2022-02-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userP',
            fields=[
                ('userP_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=256, null=True)),
                ('buy', models.CharField(max_length=256, null=True)),
                ('sellout', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('nick', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256, null=True)),
                ('password', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256, null=True)),
                ('specialty', models.CharField(max_length=256, null=True)),
                ('puissance', models.IntegerField(default=1)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
